### ISSUE TITLE
KeyError: 'low_boll'`

### ISSUE THREAD

**Issue by Delta-Trader** [tudorelu/tudorials#2]
After some time the code throws this error in regard to this pair and line

buy_price = 0.98 * df['low_boll'][i]

 tries to access a column that isn't in the dataframe. 

```
`NKNBNB
 Exception raised when trying to compute indicators on NKNBNB
Traceback (most recent call last):
Error: data_len < period
  File "C:\Users\8\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'low_boll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/8/Desktop/TradeModel.py", line 153, in <module>
    Main()
  File "C:/Users/8/Desktop/TradeModel.py", line 144, in Main
    if model.bollStrategy(len(model.df['close']) - 1):
  File "C:/Users/8/Desktop/TradeModel.py", line 123, in bollStrategy
    buy_price = 0.98 * df['low_boll'][i]
  File "C:\Users\0\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\0\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'low_boll'`
```

**Comment by tudorelu** [comment]
Hey man, this is the key: Error: data_len < period

It’s because the pair NKNBNB is new lay listed on Binance.  in order to compute the Bollinger band we need to look back in time at the 30 previous price points ( whether it’s the hourly or the daily, or 4h chart, then we need to look back at the previous 30 hours, 30 days or 30 *4hours) & if the time thugs pair has been listed on Binance is less than that, the error that you got will raise. 

This is for part 1, right? I think I might have fixed it for part 2. If not I will fix it for the next one :)

**Comment by Delta-Trader** [comment]
Thanks what I did was just exclude it from the search seems to work I wonder if it would be a idea to add something to this that would detect new coins listing then set the detection on a much smaller time frame.

```
def Main():
    exchange = Binance()
    symbols = exchange.GetTradingSymbols()
    for symbol in symbols:
        if exchange.GetTradingSymbols == 'NKNBNB':
            continue

        print(symbol)
        model = TradingModel(symbol)
        plot = True

```
